### ISSUE TITLE
Add Training

### ISSUE THREAD

**Issue by federicazanca** [stfc/aiida-mlip#121]

**Comment by ElliottKasoar** [comment]
Is it a problem that at the moment, we can't really load the model before calling the training CLI?

This may be changeable in the future, but at the moment, we only pass the config file to MACE, so it needs to be a label ("small") or path.

**Comment by federicazanca** [comment]
It's not a problem for me but it might be confusing for a user.
In general I think the way I wrote the ModelData should be changed because it's not even considered that it could be a label

**Comment by federicazanca** [comment]
> It's not a problem for me but it might be confusing for a user. In general I think the way I wrote the ModelData should be changed because it's not even considered that it could be a label

The only problem is I am not sure how to change it cause ModelData has to be a file but if we want to do it I'll figure a way

**Comment by ElliottKasoar** [comment]
The label doesn't provide particularly good provenance, since you need to know the version of MACE, which is probably only a dependency via janus (and even then it's not the nicest to unravel exactly what model was used), so you don't necessary have to support it.

**Comment by alinelena** [comment]
now we are in a small pickle since we do both training and fine tunign compact.
for training the model is an ouput
for fine tunning we have a model as an input( eg foundation model) another as an output

**Comment by ElliottKasoar** [comment]
> now we are in a small pickle since we do both training and fine tunign compact. for training the model is an ouput for fine tunning we have a model as an input( eg foundation model) another as an output

Can we not have "optional" inputs?

If not, we can still just treat them independently at this level, as if the janus commands were different?

**Comment by federicazanca** [comment]
a the moment I'm just implementing the training with the config.
Things to do:
- [ ] check if paths of files for **train test valid** exist, if not: error
- [ ] are there any other input files that might be given that I'm not considering? @ElliottKasoar 

- [ ] check names of the folders if given: 
- [ ] some outputs are by default put in some subfolders: **checkpoints, logs, results** , so it should always be programmed to read them
- [ ] some other outputs by default will go in the folder where the calc is run, but that can be set differently, so also handle this (eg models, and are there others? @ElliottKasoar )

I have decided also to add the fine-tuning later, even if it's just a keyword cause Alin says that there might be some other inputs maybe to validate?

**Comment by ElliottKasoar** [comment]
> a the moment I'm just implementing the training with the config. Things to do:
> 
> * [ ]  check if paths of files for **train test valid** exist, if not: error
> * [ ]  are there any other input files that might be given that I'm not considering? @ElliottKasoar
> * [ ]  check names of the folders if given:
> * [ ]  some outputs are by default put in some subfolders: **checkpoints, logs, results** , so it should always be programmed to read them
> * [ ]  some other outputs by default will go in the folder where the calc is run, but that can be set differently, so also handle this (eg models, and are there others? @ElliottKasoar )
> 
> I have decided also to add the fine-tuning later, even if it's just a keyword cause Alin says that there might be some other inputs maybe to validate?

There's also an optional statistics file (`statistics_file`) for the inputs.

I can't think of any other inputs/outputs, but @alinelena is probably more familiar.
