### ISSUE TITLE
fix results dictionary

### ISSUE THREAD

**Issue by federicazanca** [stfc/aiida-mlip#135]

**Comment by ElliottKasoar** [comment]
For context, what is the actual bug?

**Comment by federicazanca** [comment]
> For context, what is the actual bug?

good point as I didn't write anything.
when you did `verdi calcjob res`, which is the cli command to output the results dictionary of a calculation, some important output info (eg the energy) were not outputted. This is because I was reading the xyz output without using the right format. now I changed the format and it works.

**Comment by ElliottKasoar** [comment]
Interesting, thanks.

I've never needed to specify extxyz, and I've definitely managed to access energies from janus outputs via ase..io.read.

Is the file format definitely the problem?

**Comment by alinelena** [comment]
i think is more complex... atleast the way in which worked for Federica in aiida was normal xyz. it may be some peculiarity with using read(Path()) without format. on aiida level the output is always xyz.
