### ISSUE TITLE
deployment - pypi

### ISSUE THREAD

**Issue by alinelena** [stfc/aiida-mlip#17]

**Comment by ElliottKasoar** [comment]
I think this will be covered by the template action: https://github.com/stfc/aiida-mlip/blob/main/.github/workflows/publish-on-pypi.yml, which should publishe when we tag a version.

As discussed with @alinelena, we may want to publish a latest version as well as stable, tagged versions.

**Comment by alinelena** [comment]
is not really working

**Comment by ElliottKasoar** [comment]
Resolved by https://github.com/stfc/aiida-mlip/commit/600a256a94b8d5279bbf979a783afe709be9fe46.

See: https://pypi.org/project/aiida-mlip/

A few issues remain as described in #71 and #72
