### ISSUE TITLE
Publish code coverage

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/aiida-mlip#60]
We currently generate code coverage during the [CI workflow](https://github.com/stfc/aiida-mlip/blob/main/.github/workflows/ci_orig.yml#L51), but do not publish/report it clearly.

Based on the [aiida-gromacs](https://github.com/PSDI-Biomolecular-team/aiida-gromacs/blob/master/.github/workflows/ci.yml#L61) workflow, it looks relatively straightforward to modify the workflow to report our results to coveralls, if we're happy to stick with this.

I believe we also need to register this repository on coveralls, and probably generate/add a token.

This should hopefully also fix the badge in the README, which is already set up to link to coveralls.

**Comment by alinelena** [comment]
we may want to consider this also 
https://hackernoon.com/adding-test-coverage-badge-on-github-without-using-third-party-services
always is nice to reduce the number of services one depends on

**Comment by ElliottKasoar** [comment]
If it were something where we were setting up from scratch like new CI for travis I'd definitely avoid a new service, but with where we are already, my inclination is to get it published on coveralls first, since I think we're basically ready with minimal work.

Arguably there's a positive effect on perception with "external" validation too.

Either way, it's definitely useful to be aware of alternatives and potentially consider moving longer term.

**Comment by alinelena** [comment]
i need to check how is in github but in gitlab is really 2 lines to set it up.
https://gitlab.com/ccp5/dlpoly-py/-/blob/devel/.gitlab-ci.yml?ref_type=heads
