### ISSUE TITLE
aiida cli

### ISSUE THREAD

**Issue by federicazanca** [stfc/aiida-mlip#92]
to do later, but as a reminder

#[tool.poetry.plugins."aiida.cmdline.data"]
#"mlip" = "aiida_mlip.cli:data_cli"

also look into this? (from the initial readme)
The plugin also includes verdi commands to inspect its data types:
```shell
verdi data mlip list
verdi data mlip export <PK>
```

**Comment by ElliottKasoar** [comment]
I think this was resolved (e.g. the commented out lines were removed in #84).
